version: "3.8"
services:
  kpis:
    build: .
    ports:
      - "8009:8009"
    depends_on:
      - mysql_container
    networks:
      - app-network

  mysql_container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=network_insights
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
